# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-11-17 11:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(blank=True, null=True)),
                ('lat_long', models.CharField(max_length=100)),
                ('is_geocoded', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=250)),
                ('uploaded_time', models.DateTimeField(default=datetime.datetime.now)),
                ('size', models.IntegerField()),
                ('geocoding_status', models.IntegerField(default=1)),
            ],
        ),
        migrations.AddField(
            model_name='location',
            name='upload',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='csvcoder.Upload'),
        ),
    ]
